# =====================================================
# Common Application Configuration
# =====================================================

# Application name (single source of truth)
spring.application.name=springboot-ci-demo-with-aws

# Profile will be set by Jenkins at runtime (dev / qa)
spring.profiles.active=default

# =====================================================
# Logging (safe defaults)
# =====================================================
logging.level.root=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
